name: Deploy Landings to Pages

on:
  push:
    branches: ["main"]
    paths:
      - 'web_landing_page/deploy/**' # Trigger when deploy folder changes
      - 'mind/**' # Trigger when new MIND project changes

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Build MIND Page
        working-directory: ./mind
        run: |
          npm ci
          npm run build
          mkdir -p ../web_landing_page/deploy/mind
          cp -r dist/* ../web_landing_page/deploy/mind/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Deploy ONLY the 'deploy' folder, so index.html is at root of the site
          path: 'web_landing_page/deploy'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
